language: php

php:
    - '7.4'

install: composer install --no-progress
script:
  - vendor/bin/phpstan analyse --no-progress -l 7 -c ./phpstan.neon src
  - php -d "zend_extension=xdebug" vendor/bin/phpunit --coverage-text
